apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
type: Opaque
data:
  jwt-secret: ${JWT_SECRET_BASE64}
  database-url: ${AUTH_DB_URL_BASE64}
---
apiVersion: v1
kind: Secret
metadata:
  name: product-secrets
type: Opaque
data:
  database-url: ${PRODUCT_DB_URL_BASE64}
---
apiVersion: v1
kind: Secret
metadata:
  name: order-secrets
type: Opaque
data:
  database-url: ${ORDER_DB_URL_BASE64} 