apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.authService.service.type }}
  selector:
    app: auth-service
  ports:
  - port: {{ .Values.authService.service.port }}
    targetPort: 8001
    protocol: TCP
    name: http 