apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.apiGateway.service.type }}
  selector:
    app: api-gateway
  ports:
  - port: {{ .Values.apiGateway.service.port }}
    targetPort: {{ .Values.apiGateway.service.targetPort }}
    protocol: TCP
    name: http 