apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.productService.service.type }}
  selector:
    app: product-service
  ports:
  - port: {{ .Values.productService.service.port }}
    targetPort: 8002
    protocol: TCP
    name: http 