apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: order-service
        image: microservicesdemodevacred7ulf27.azurecr.io/microservices-demo/order-service:latest
        ports:
        - containerPort: 8003
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8003
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
        - name: SQLALCHEMY_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: order-secrets
              key: SQLALCHEMY_DATABASE_URL
        - name: PRODUCT_SERVICE_URL
          value: "http://product-service:8002"
        - name: REDIS_URL
          value: "redis://redis:6379/2" 