apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.orderService.replicas }}
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: order-service
        image: {{ .Values.orderService.image }}
        ports:
        - containerPort: 8003
        resources:
          {{- toYaml .Values.orderService.resources | nindent 10 }}
        env:
        - name: SQLALCHEMY_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: order-secrets
              key: SQLALCHEMY_DATABASE_URL
        - name: PRODUCT_SERVICE_URL
          value: {{ .Values.orderService.env.PRODUCT_SERVICE_URL | quote }}
        - name: REDIS_URL
          value: {{ .Values.orderService.env.REDIS_URL | quote }}
        livenessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8003
          initialDelaySeconds: 5
          periodSeconds: 10 