apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.orderService.service.type }}
  selector:
    app: order-service
  ports:
  - port: {{ .Values.orderService.service.port }}
    targetPort: 8003
    protocol: TCP
    name: http 